spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 5
      max-active: 10
      filters: stat,wall
      filter:
        config:
          enabled: true